version: "3"

services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: gradle run --args="8080"
    volumes:
      - ./:/home/app/
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: "mysql://mysql:3306/TodoManager"
      DATABASE_USER: "user"
      DATABASE_PASSWORD: "password"
      CLASSPATH: "./build/libs/TodoManager-1.0-SNAPSHOT-all.jar"
      TZ: "Asia/Tokyo"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "TodoManager"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      TZ: "Asia/Tokyo"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d

volumes:
  mysql:
